# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stemdemoapp', '0003_auto_20170907_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranscriptAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranscriptLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=65536)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemdemoapp.TranscriptAuthor')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stemdemoapp.Transcript')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
